# Example/Documentation for this file
# https://fshschool.org/docs/sushi/configuration/#exhaustive-example

id: ch.fhir.ig.ch-etoc
canonical: http://fhir.ch/ig/ch-etoc
name: CH_eTOC
title: "CH eTOC (R4)"
description: Implementation guide for eTOC based on CH ORF
status: active
license: CC0-1.0
copyright: CC0-1.0
jurisdiction: urn:iso:std:iso:3166#CH
date: 2025-12-16
version: 3.0.1
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: trial-use # ci-build | draft | qa-preview | ballot | trail-use | release | update | normative+trail-use
publisher:
  name: HL7 Switzerland
contact:
  - name: Juerg P. Bleuer
    telecom:
      - system: url
        value: https://www.hl7.ch
dependencies:
  ch.fhir.ig.ch-core: 6.0.0
  ch.fhir.ig.ch-orf: 3.0.2
  
pages:
  index.md:
    title: Home
  usecase-english.md:
    title: Use Cases
  usecase-german.md:
    title: Anwendungsf√§lle
  questionnaire-form.html:
    title: Questionnaire
  profiles.html:
    title: Profiles
  extensions.html:
    title: Extensions
  changelog.md:
    title: Changelog

parameters:
  excludettl: true
  allow-extensible-warnings: true
  display-warnings: true  
  path-expansion-params: '../../expansion-params.json'  # for using SNOMED CT Swiss Extension
  pin-canonicals: pin-multiples
